git:
  depth: false

notifications:
  email: false

language: java
jdk: oraclejdk8

env:
  global:
  - TERM=dumb

addons:
  apt:
    packages:
    - bash
    - curl
    - jq
    - python-pip
#    - oracle-java8-installer
#    - oracle-java8-set-default

install: true
before_install:
- sudo pip install httpie >/dev/null 2>&1
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 8080 3000 80 >/dev/null
- java -version
- javac -version

script:
- export root=$(pwd)
#
- ./mvnw >/dev/null
#
- ./mvnw -pl :java-ee-payara-rest-services -Pbundle >/dev/null
- java -jar ./java-ee-payara/java-ee-payara-rest-services/target/*-microbundle.jar &
- wait_for 8080
- sleep 15
- http :8080 || true
- http -a anything:here :8080
- http -a abc:xyz :8080/resp\?page=-4
- http -a qwerty:123 :8080/json\?page=-4 || true
- http -a qwerty:123 :8080/ data=ololo
- http -a qwerty:123 :8080/ data='ololo trololo'
- http -a anything:here :8080
- stop_any 80 8080
#
- java -jar ./dropwizard/dropwizard-rest-services/target/dropwizard-*.jar server ./dropwizard/dropwizard-rest-services/config.yml &
- wait_for 9000
- sleep 20
- http :9000 || true
- http -a anything:here :9000
- http -a qwerty:123 :9000/json\?page=-4 || true
- http -a qwerty:123 :9000/ data=ololo
- http -a qwerty:123 :9000/ data='ololo trololo'
- http -a anything:here :9000
- stop_any 80 9000
#
- ./mvnw -pl :struts-rest-services clean package >/dev/null
- bash ./struts/struts-rest-services/target/*-thorntail.jar &
- wait_for 8080
- sleep 10
- http :8080
- http :8080/about
- http :8080/api
- http :8080/api/health
- http :8080/api/fail
- http :8080/api/not-found
- http :8080/not-found
- http :8080/api/message/find-all
- http :8080/api/message/save message=hello
- http :8080/api/message/find-all
- stop_any 80 8080
