notifications:
  email: false
git:
  quiet: true
  depth: false
language: java
jdk: openjdk8
python: 3.7
os: linux
arch: amd64
addons:
  apt:
    update: true
    packages:
      - wget
      - curl
      - sudo
      - lsof
      - python3-pip
install: true
before_install:
  - |
    if [ ! -f ${HOME}/.local/daggerok/bash-functions/master/main.bash ] ; then
      mkdir -p ${HOME}/.local/daggerok/bash-functions/master ;
      curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash > ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
    fi
    source ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
  - stop_any 80 8001 8002 8080 5432
  #
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user --upgrade pip setuptools
  - pip install --user --upgrade httpie
jobs:
  include:
    - stage: test
      jdk: openjdk11
      name: openjdk11 java-ee-payara-rest-services
      script:
        - ./mvnw
        - ./mvnw -pl :java-ee-payara-rest-services -Pbundle
        - java -Djava.net.preferIPv4Stack=true -jar ./java-ee-payara/java-ee-payara-rest-services/target/*-microbundle.jar &
        - wait_for 8080
        - sleep 13
        - http :8080 || echo unauthorized expected
        - http -a anything:here :8080
        - http -a abc:xyz :8080/resp\?page=-4
        - http -a qwerty:123 :8080/json\?page=-4 || echo 400 error expected
        - http -a qwerty:123 :8080/ data=ololo
        - http -a qwerty:123 :8080/ data='ololo trololo'
        - http -a anything:here :8080
        - stop_any 80 8080
    - stage: test
      jdk: openjdk8
      name: openjdk8 java-ee-payara-rest-services
      script:
        - ./mvnw
        - ./mvnw -pl :java-ee-payara-rest-services -Pbundle
        - java -Djava.net.preferIPv4Stack=true -jar ./java-ee-payara/java-ee-payara-rest-services/target/*-microbundle.jar &
        - wait_for 8080
        - sleep 35
        - http :8080 || true
        - http -a anything:here :8080
        - http -a abc:xyz :8080/resp\?page=-4
        - http -a qwerty:123 :8080/json\?page=-4 || true
        - http -a qwerty:123 :8080/ data=ololo
        - http -a qwerty:123 :8080/ data='ololo trololo'
        - http -a anything:here :8080
        - stop_any 80 8080
    - stage: test
      jdk: openjdk11
      name: openjdk11 dropwizard-rest-services
      script:
        - ./mvnw
        - java -Djava.net.preferIPv4Stack=true -jar ./dropwizard/dropwizard-rest-services/target/dropwizard-*.jar server ./dropwizard/dropwizard-rest-services/config.yml &
        - wait_for 9000
        - sleep 35
        - http :9000 || true
        - http -a anything:here :9000
        - http -a qwerty:123 :9000/json\?page=-4 || true
        - http -a qwerty:123 :9000/ data=ololo
        - http -a qwerty:123 :9000/ data='ololo trololo'
        - http -a anything:here :9000
        - stop_any 80 9000
    - stage: test
      jdk: openjdk8
      name: openjdk8 dropwizard-rest-services
      script:
        - ./mvnw
        - java -Djava.net.preferIPv4Stack=true -jar ./dropwizard/dropwizard-rest-services/target/dropwizard-*.jar server ./dropwizard/dropwizard-rest-services/config.yml &
        - wait_for 9000
        - sleep 35
        - http :9000 || true
        - http -a anything:here :9000
        - http -a qwerty:123 :9000/json\?page=-4 || true
        - http -a qwerty:123 :9000/ data=ololo
        - http -a qwerty:123 :9000/ data='ololo trololo'
        - http -a anything:here :9000
        - stop_any 80 9000
    - stage: test
      jdk: openjdk11
      name: openjdk11 struts-rest-services
      script:
        - ./mvnw
        - ./mvnw -pl :struts-rest-services clean package
        - java -Djava.net.preferIPv4Stack=true -jar ./struts/struts-rest-services/target/*-thorntail.jar &
        - wait_for 8080
        - sleep 35
        - http :8080
        - http :8080/about
        - http :8080/api
        - http :8080/api/health
        - http :8080/api/fail
        - http :8080/api/not-found
        - http :8080/not-found
        - http :8080/api/message/all
        - http :8080/api/message/one id=ololo
        - http :8080/api/message/new message=ololo
        - http :8080/api/message/new message=trololo
        - http :8080/api/message/all
        - stop_any 80 8080
    - stage: test
      jdk: openjdk8
      name: openjdk8 struts-rest-services
      script:
        - ./mvnw
        - ./mvnw -pl :struts-rest-services clean package
        - java -Djava.net.preferIPv4Stack=true -jar ./struts/struts-rest-services/target/*-thorntail.jar &
        - wait_for 8080
        - sleep 35
        - http :8080
        - http :8080/about
        - http :8080/api
        - http :8080/api/health
        - http :8080/api/fail
        - http :8080/api/not-found
        - http :8080/not-found
        - http :8080/api/message/all
        - http :8080/api/message/one id=ololo
        - http :8080/api/message/new message=ololo
        - http :8080/api/message/new message=trololo
        - http :8080/api/message/all
        - stop_any 80 8080
    - stage: test
      jdk: openjdk11
      name: openjdk11 versions display-dependency-updates
      script: ./mvnw versions:display-dependency-updates
    - stage: test
      jdk: openjdk8
      name: openjdk8 versions display-dependency-updates
      script: ./mvnw versions:display-dependency-updates
cache:
  pip: true
  packages: true
  directories:
    - struts/struts-rest-services/src/main/js/node_modules
    - struts/struts-rest-services/target/node
    - ~/.local/daggerok
    - ~/.mvn
