server:
  applicationConnectors:
  - type: http
    port: 9000
  adminConnectors:
  - type: http
    port: 9001
dataSourceFactory:
  driverClass: org.h2.Driver
  user: sa
  password: sa
  url: jdbc:h2:mem:dropwizard-rest-services;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  properties:
    charSet: UTF-8
    hibernate.hbm2ddl.auto: create
    validationQuery: "/* application healthcheck */ SELECT 1"
